### ISSUE TITLE
MouseOver of skill charts

### ISSUE THREAD

**Issue by annagclaire** [matfin/mattfinucane.com#39]
When you moues-over the chart the text fades in: 100% Expert. The percentage ist defined by the coloured chart. The colour of the chart doesnt need the colour change.

see attached screenshot:

![screen shot 2017-05-28 at 22 44 17](https://cloud.githubusercontent.com/assets/8093950/26532035/3f5fde18-43f7-11e7-95b2-a906d7635543.png)

**Comment by matfin** [comment]
A fix for this has been pushed to https://staging.mattfinucane.com.
