### ISSUE TITLE
Link Style / Underline

### ISSUE THREAD

**Issue by annagclaire** [matfin/mattfinucane.com#40]
Improvement of the underline of a linked word.

On the Wired Homepage you can maybe see how they build it. I also like the mouse-over effect:
https://www.wired.com/2017/05/gif-turns-30-ancient-format-changed-internet/

![screen shot 2017-05-28 at 22 52 11](https://cloud.githubusercontent.com/assets/8093950/26532082/6aa32d2c-43f8-11e7-945a-7403c1312c64.png)

**Comment by matfin** [comment]
A fix for this has been pushed to https://staging.mattfinucane.com.

**Comment by annagclaire** [comment]
Perfect now!
