### ISSUE TITLE
Position of main title

### ISSUE THREAD

**Issue by annagclaire** [matfin/mattfinucane.com#41]
Adjustment of the position of the title. 

Have a look at the three screen examples. Please check if its possible if the title is shifted more to the right.

![postion-of-title-1](https://cloud.githubusercontent.com/assets/8093950/26532283/c63ec728-43fc-11e7-9cd9-0f4362a99678.jpg)

![postion-of-title-2](https://cloud.githubusercontent.com/assets/8093950/26532282/c63dea24-43fc-11e7-84b6-d48bc90ed107.jpg)

![postion-of-title-3](https://cloud.githubusercontent.com/assets/8093950/26532281/c63b28c0-43fc-11e7-99c6-9d9d0cf86e02.jpg)

**Comment by matfin** [comment]
A fix for this has been pushed to https://staging.mattfinucane.com.
