### ISSUE TITLE
Project chart size

### ISSUE THREAD

**Issue by annagclaire** [matfin/mattfinucane.com#43]
The project charts look quite small. i checked it with the design. 
 Is it possible to increase the width or was there a reason to put it in a width of 793 px?

in the design we have a width of 1080px:
![mattfinucane-1080px](https://cloud.githubusercontent.com/assets/8093950/26549819/1fa4a30e-447b-11e7-8c97-d4c4e54cac77.jpg)

Also I was thinking that the Subheadline is fading in when the User is doing a mouse-over.

**Comment by matfin** [comment]
A fix for this has been pushed to https://staging.mattfinucane.com

**Comment by annagclaire** [comment]
Okay cool!

Can we put a minimum height in for the charts? At the moment the size is measured by the leangth of the content.

 And what do you think about the moues-over? So the Subheadline is fading in when the User is doing a mouse-over.
