### ISSUE TITLE
main.css generated in static/js directory, not updating

### ISSUE THREAD

**Issue by sagannotcarl** [matfin/mattfinucane.com#52]
Hey Matt,
I was struggling to get something like this set up when I stumbled onto your site. Thanks so much for sharing all of this work!

Almost everything worked perfectly but I'm having some trouble with updating the scss. When I first ran `docker-compose up` there was no `static/css` directory, but there was a `main.css` in the `static/js` directory. Then when I make changes to scss files I see in the logs that the `mf_webpack_dev` container is seeing the changes, but no further css files are written (to `static/css` or `static/js`. 

I also don't see where in the configuration those paths are set.

If you have any suggestions for troubleshooting this I would really appreciate it!

**Comment by matfin** [comment]
Hey,

Just got this now. I published a release for the site that should correct this issue. I fixed the webpack config and updated all npm dependencies. Can you please check again?

Thanks,

Matt

**Comment by sagannotcarl** [comment]
Works great. Thanks again!
